
server{
    listen 80;

    # 1. Serve the frontend HTML/JS
    location / {
        root /usr/share/nginx/html;
        index index.html login.html; # the first index is a keyword for default page

        #this prevents 404's when people refresh the page
        try_files $uri $uri/ /index.html;
    }

    # 2. Secretly proxy API request to Django
    location /api/ {
        # 'backend' matches the service name in the docker-compose.yaml
        proxy_pass http://backend:8000;

        # Pass along the original IP so that django knows who's calling
        proxy_set_header Host $host; ## basically passing "taskmaster.com/"
        proxy_set_header X-Real-IP $remote_addr; # passing the users ip
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # passing the ip's of any intermediatories if present, like cloudfare maybe, but order remains the same, first is the users' ip
        # more like a track of ip's
    }

    # 3. Django Admin Panel
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    # 4. Django Static Files (CSS , JS for Swagger and Admin)
    location /static/ {
        alias /django_static/;
    }



    # 5. Proxy websocket connection for daphne
    location /ws/ {
        proxy_pass http://backend:8000;

        # three lines for websocket connection
        # host, upgrade:websocket, connection:upgrade
        # websockets require http 1.1 version
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}